### ISSUE TITLE
No funciona la pantalla

### ISSUE THREAD

**Issue by misees** [utvoluntariado/medidor-co2#1]
Hola! 

He montado el medidor según las instrucciones y puedo leer la medida a través de la wifi, pero la pantalla no funciona.
Al alimentarla se ilumina, pero no muestra ningún dato.

Pensaba en volver a integrar el driver de la pantalla, pero no se muy bien como generar el proyecto.

¿Tienes alguna idea sobre lo que podría mirar?

Muchas gracias por tu trabajo. La verdad es que esta todo muy bien explicado.

**Comment by jorgej-ramos** [comment]
Gracias por tu comentario y por montar el medidor. Solo tengo una pregunta:

¿La pantalla usada es la misma que la que se propone en la instrucciones? Si no lo es probablemente se deba a un tema de drivers solucionadle muy fácilmente.

Probemos por ahí. De todos modos mañana haré una prueba de nuevo con mi set para ver que puede estar fallando.

**Comment by misees** [comment]
Gracias por responder tan rapido.

Si, la compre en el enlace de amazon que pusiste.

**Comment by jorgej-ramos** [comment]
No te preocupes buscaré el problema y encontraremos una solución. Si puedes leer la medición por WiFi el sistema está funcionando como debe.

Probablemente se deba a alguna conexión algo floja. Mientras hago pruebas te sugiero repasar de nuevo el cableado.

Volveré con más info. Gracias una vez más.

**Comment by jorgej-ramos** [comment]
Hola disculpa la tardanza en contestar. He realizado pruebas y no he encontrado problemas con el ser que tengo aquí.

Mañana no obstante trataré de acometer el problema desde otro punto de vista. Mientras tanto ¿pudiste revisar bien las conexiones de la pantalla?

Por otro lado, ¿que fuente está alimentando de corriente el sistema?

Gracias por tu paciencia

**Comment by jorgej-ramos** [comment]
Tras 4 días sin respuesta cierro esta incidencia. En caso de necesario se reabrirá. Gracias por los comentarios.
