### ISSUE TITLE
Compatibilidad con Raspberry Pi 3B

### ISSUE THREAD

**Issue by dapandido** [utvoluntariado/medidor-co2#2]
Buenas noches , gracias por el proyecto , lo he intentado hacer con una Raspberry  3B pero no consigo hacerlo funcionar , en principio el software debería ser compatible no ? he probado en dos placas diferentes y nada , ni red wifi y la pantalla arranca blanca y después se queda en negro

Gracias por la ayuda

**Comment by jorgej-ramos** [comment]
Buenas noches y gracias por sus comentarios. No he podido testear el software sobre una RPi 3. 

No obstante puedo conseguir alguna y probarlo para comprobar el funcionamiento.

Mientras tanto, ¿cual es la fuente que alimenta el sistema? Si todo está bien, probablemente se deba a una incompatibilidad del último sistema Raspbian sobre el que está montando el medidor.

Este medidor ha sido probado en una RPi 4 y en una RPi Zero. No obstante haré la pruebas adecuadas sobre una RPi 3 y volveré con los resultados.

**Comment by dapandido** [comment]
Buenos dias , gracias por su tiempo , la fuente es de 5 V 3000 MA por lo que debería ser suficiente , desde luego es raro que funciona en esas dos placas y no en la 3 , a ver si voy tener el sensor defectuoso ( cada pocos segundos se ilumina un pequeño destello rojo en las zonas por donde entiendo que mide ) Si no le supone mucho trabajo , esperare a sus pruebas con la RP3

Saludos y gracias de nuevo

**Comment by jorgej-ramos** [comment]
Tratare de tardar lo menos posible. Volveré aquí con resultados.

**Comment by jorgej-ramos** [comment]
Unas pruebas preliminares me indican que quizá el problema esté en la tarjeta WiFi de la placa Raspberry Pi 3. Muy probablemente debido un fallo de implementación por mi parte, al no disponer de todos los modelos de Raspberry Pi durante el desarrollo.
Su sensor lo más probable es que esté en perfectas condiciones.

No obstante y partiendo de este punto, espero proporcionarle una solución lo antes posible.
Lamento las molestas y la espera, pero los recursos son muy limitados.

**Comment by dapandido** [comment]
Gracias por la respuesta , tome el tiempo que necesite , si desea implementarlo , ya bastante ha hecho publicando el proyecto .

Saludos y gracias

**Comment by jorgej-ramos** [comment]
He podido recibir hoy una RPi 3B con la mala suerte de estar defectuosa. 

Seguiré informándole.
Gracias por su paciencia.

**Comment by dapandido** [comment]
Buenos dias , no se preocupe ,agradezco sus esfuerzos , por mi parte no hay ninguna prisa , si le puedo ayudar en algo no dude en pedirlo 

Saludos  y gracias

**Comment by jorgej-ramos** [comment]
Se ha reportado un bug con la pantalla en ciertas RPi Zero (#4). Se publicará una nueva versión próximamente. Quizá pueda probar esta nueva imagen que se va a subir para comprobar si el problema se soluciona.

Lamento la tardanza de casi un mes, pero me ha sido imposible hacerlo antes.

**Comment by jorgej-ramos** [comment]
Se cierra esta incidencia al no tener respuesta.
