### ISSUE TITLE
Compatibilidad 

### ISSUE THREAD

**Issue by dapandido** [utvoluntariado/medidor-co2#3]
Buenas noches , gracias por el proyecto , lo he intentado hacer con una Raspberry  3B pero no consigo hacerlo funcionar , en principio el software debería ser compatible no ? he probado en dos placas diferentes y nada , ni red wifi y la pantalla arranca blanca y después se queda en negro

Gracias por la ayuda

**Comment by jorgej-ramos** [comment]
Este issue está duplicado en [#2](https://github.com/utvoluntariado/medidor-co2/issues/2). Se continúa allí la conversación.

**Comment by jorgej-ramos** [comment]
Se ha reportado un bug con la pantalla en ciertas RPi Zero (https://github.com/utvoluntariado/medidor-co2/issues/4). Se publicará una nueva versión próximamente. Quizá pueda probar esta nueva imagen que se va a subir para comprobar si el problema se soluciona.

Lamento la tardanza de casi un mes, pero me ha sido imposible hacerlo antes.
