### ISSUE TITLE
Problema con pantalla

### ISSUE THREAD

**Issue by otxiko** [utvoluntariado/medidor-co2#4]
Buenas tardes. He estudiado y montado el proyecto al completo. La pantalla recibe alimentación pero se queda en negro. ¿Se le ha presentado este problema a alguien más? Los componentes son todos de la lista proporcionada en el proyecto, incluida la pantalla. De hecho, le he añadido las 4 conexiones del otro lateral, como indican las fotos de Amazon, por si fuera eso, pero el resultado en el mismo. 
![71Zk+Lb85QL _SL1500_](https://user-images.githubusercontent.com/80711608/111201873-83b92d00-85c3-11eb-9347-d320e4345fe0.jpg)

Sí que se ve correctamente cuando conecto la Raspberry por miniHDMI a una pantalla "normal". Seguiré investigando.

Gracias por su tiempo y dedicación.

**Comment by jorgej-ramos** [comment]
Buenas tardes gracias por tomarse el tiempo en montar el sistema.
Una persona más ha reportado este problema pero no ha habido más. No obstante dos es un número suficiente para tener en cuenta una actualización que solucione bugs.

Buscaré el problema en la propia imagen del sistema que, presumiblemente, no se ha generado correctamente. 

Trataré de dar una respuesta lo antes posible.

**Comment by jorgej-ramos** [comment]
Un update sobre este bug: he pedido otra Pi Zero para poder re-testear la imagen dado que sobre la que se construyó el proyecto original ya no está disponible. Seguiré actualizando en cuanto pueda.
Gracias por mantener la paciencia.

**Comment by jorgej-ramos** [comment]
Afortunadamente he podido aislar el problema y solucionarlo. Espero poder publicar en pocas horas el parche que soluciona el problema. 

Gracias por reportar.
![image](https://user-images.githubusercontent.com/1220565/111770127-506bec00-88aa-11eb-8e0f-728caf3f97df.jpeg)
